import { Link } from 'react-router-dom'
import {
  Brain, Zap, Target, BarChart3, ArrowRight, Sparkles,
  CheckCircle, TrendingUp, Users, BookOpen, Shield
} from 'lucide-react'
import { motion } from 'framer-motion'

const features = [
  {
    icon: Brain,
    title: 'AI Profile Building',
    desc: 'Chat naturally with PathMind AI. It builds your learner profile through conversation — no boring forms.',
    color: 'bg-brand-50 text-brand-600',
  },
  {
    icon: Target,
    title: 'Skill Gap Analysis',
    desc: 'See exactly which skills you need. Our topological DAG engine sequences learning in the optimal order.',
    color: 'bg-violet-50 text-violet-600',
  },
  {
    icon: Zap,
    title: 'ML Recommendation Engine',
    desc: 'TF-IDF cosine similarity + SVD collaborative filtering score every resource. Pure math, not guesswork.',
    color: 'bg-amber-50 text-amber-600',
  },
  {
    icon: BarChart3,
    title: 'Adaptive Learning',
    desc: 'Bayesian Beta skill estimation tracks your mastery with uncertainty. Your path evolves with every assessment.',
    color: 'bg-emerald-50 text-emerald-600',
  },
]

const steps = [
  { n: '01', title: 'Tell AI your goal',       desc: 'Describe what you want to achieve in your own words.' },
  { n: '02', title: 'See your skill gaps',      desc: 'The DAG engine maps your prerequisite chain to optimal learning order.' },
  { n: '03', title: 'Get your ML roadmap',     desc: 'A structured, week-by-week path generated by hybrid ML scoring.' },
  { n: '04', title: 'Learn and adapt',          desc: 'Bayesian updates refine your model after every assessment.' },
]

const stats = [
  { value: '8+', label: 'ML Scoring Factors' },
  { value: '100%', label: 'Personalized' },
  { value: 'Real-time', label: 'Path Adaptation' },
  { value: 'Open', label: 'Source & Free' },
]

export default function Landing() {
  return (
    <div className="min-h-screen bg-white text-text-primary overflow-x-hidden">

      {/* ── Top Nav ──────────────────────────────────────── */}
      <nav className="sticky top-0 z-50 bg-white/80 backdrop-blur-md border-b border-surface-200">
        <div className="max-w-6xl mx-auto px-6 py-4 flex items-center justify-between">
          <div className="flex items-center gap-2.5">
            <div className="w-9 h-9 rounded-xl bg-gradient-to-br from-brand-500 to-violet-600 flex items-center justify-center shadow-brand-sm">
              <Brain className="w-5 h-5 text-white" />
            </div>
            <span className="font-bold text-text-primary text-lg">PathMind AI</span>
          </div>
          <div className="flex items-center gap-3">
            <Link to="/login" className="btn-ghost text-sm">Sign in</Link>
            <Link to="/register" className="btn-primary text-sm">Get started free</Link>
          </div>
        </div>
      </nav>

      {/* ── Hero ─────────────────────────────────────────── */}
      <section className="max-w-6xl mx-auto px-6 pt-20 pb-16">
        <div className="grid lg:grid-cols-2 gap-12 items-center">
          {/* Left copy */}
          <motion.div
            initial={{ opacity: 0, y: 24 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.55 }}
          >
            <div className="inline-flex items-center gap-2 px-3.5 py-1.5 rounded-full bg-brand-50 border border-brand-100 text-brand-700 text-sm font-medium mb-6">
              <Sparkles className="w-3.5 h-3.5" />
              Powered by Gemini AI + Proper ML
            </div>
            <h1 className="text-5xl lg:text-6xl font-black leading-tight text-text-primary mb-5">
              Your goal.{' '}
              <span className="gradient-text">Your pace.</span>
              <br />Your path.
            </h1>
            <p className="text-lg text-text-secondary leading-relaxed mb-8">
              Tell our AI what you want to achieve. It builds your learner profile,
              identifies skill gaps with a knowledge graph, and generates a
              personalized roadmap — scored by real ML algorithms.
            </p>
            <div className="flex flex-col sm:flex-row gap-3 mb-8">
              <Link to="/register" className="btn-primary text-base px-7 py-3.5">
                Start My Journey <ArrowRight className="w-5 h-5" />
              </Link>
              <Link to="/login" className="btn-secondary text-base px-7 py-3.5">
                Sign in
              </Link>
            </div>
            <p className="text-xs text-text-muted">
              Free forever · No credit card · Runs locally
            </p>
          </motion.div>

          {/* Right: demo chat card */}
          <motion.div
            initial={{ opacity: 0, y: 36 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.65, delay: 0.2 }}
            className="relative"
          >
            {/* Decorative glow */}
            <div className="absolute -inset-4 bg-gradient-to-br from-brand-100 to-violet-100 rounded-3xl blur-2xl opacity-60" />
            <div className="relative card shadow-card-lg rounded-3xl overflow-hidden">
              {/* Mock browser bar */}
              <div className="flex items-center gap-1.5 px-4 py-3 bg-surface-100 border-b border-surface-200">
                <div className="w-3 h-3 rounded-full bg-red-400" />
                <div className="w-3 h-3 rounded-full bg-amber-400" />
                <div className="w-3 h-3 rounded-full bg-emerald-400" />
                <span className="ml-3 text-xs text-text-muted">PathMind AI Chat</span>
              </div>
              <div className="p-5 space-y-3 bg-surface-50">
                <div className="chat-bubble-user w-fit ml-auto">
                  I want to become a Machine Learning Engineer. I know Python basics.
                </div>
                <div className="chat-bubble-ai w-fit">
                  Great goal! 🎯 I've identified <strong>7 skill gaps</strong> using our knowledge graph.
                  Your Python foundation gives you a head start — I'll sequence learning in the optimal order.
                  How many hours per week can you dedicate?
                </div>
                <div className="chat-bubble-user w-fit ml-auto">About 8 hours per week</div>
                <div className="chat-bubble-ai w-fit">
                  Perfect. Generating your <strong>14-week roadmap</strong> now…
                  TF-IDF + collaborative filtering scored 120+ resources. Starting with
                  Statistics → NumPy → Core ML → Deep Learning → MLOps capstone. ✨
                </div>
              </div>
              {/* Stats strip */}
              <div className="grid grid-cols-3 divide-x divide-surface-200 border-t border-surface-200">
                {[['14 Weeks', 'Roadmap'], ['8 Factors', 'ML Scoring'], ['97%', 'Fit Score']].map(([val, lbl]) => (
                  <div key={lbl} className="py-3 text-center">
                    <p className="text-sm font-bold text-brand-600">{val}</p>
                    <p className="text-xs text-text-muted">{lbl}</p>
                  </div>
                ))}
              </div>
            </div>
          </motion.div>
        </div>
      </section>

      {/* ── Stats bar ────────────────────────────────────── */}
      <section className="bg-brand-600">
        <div className="max-w-5xl mx-auto px-6 py-8">
          <div className="grid grid-cols-2 lg:grid-cols-4 gap-6 text-center">
            {stats.map(s => (
              <div key={s.label}>
                <p className="text-3xl font-black text-white">{s.value}</p>
                <p className="text-sm text-brand-200 mt-1">{s.label}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ── Features ─────────────────────────────────────── */}
      <section className="max-w-6xl mx-auto px-6 py-20">
        <div className="text-center mb-14">
          <h2 className="text-3xl font-bold mb-3 text-text-primary">
            Not just recommendations.{' '}
            <span className="gradient-text">A complete ML system.</span>
          </h2>
          <p className="text-text-secondary max-w-xl mx-auto">
            Every feature built on proper algorithms — from topological graph traversal
            to Bayesian skill estimation.
          </p>
        </div>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          {features.map((f, i) => (
            <motion.div
              key={i}
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.45, delay: i * 0.08 }}
              className="card-hover"
            >
              <div className={`w-11 h-11 rounded-xl flex items-center justify-center mb-4 ${f.color}`}>
                <f.icon className="w-5 h-5" />
              </div>
              <h3 className="font-bold text-text-primary mb-2">{f.title}</h3>
              <p className="text-sm text-text-secondary leading-relaxed">{f.desc}</p>
            </motion.div>
          ))}
        </div>
      </section>

      {/* ── ML Algorithms callout ────────────────────────── */}
      <section className="bg-surface-100 border-y border-surface-200 py-16">
        <div className="max-w-5xl mx-auto px-6">
          <div className="text-center mb-10">
            <h2 className="text-2xl font-bold text-text-primary mb-2">The Algorithms Behind PathMind</h2>
            <p className="text-text-secondary text-sm">Real math powering real personalization</p>
          </div>
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
            {[
              { label: 'TF-IDF Cosine Similarity', desc: 'Semantic match between your goal text and resource descriptions', tag: 'Content-Based' },
              { label: 'SVD Collaborative Filter', desc: 'Matrix factorization finds "learners like you also completed X"', tag: 'Collaborative' },
              { label: 'Bayesian Beta Estimation', desc: 'Models skill mastery as Beta(α,β) — tracks certainty, not just score', tag: 'Bayesian ML' },
              { label: 'Kahn\'s Topological Sort', desc: 'BFS on skill dependency DAG guarantees optimal prerequisite ordering', tag: 'Graph Algorithms' },
              { label: 'Jaccard Set Similarity', desc: 'Goal relevance scored via intersection-over-union of skill sets', tag: 'Set Theory' },
              { label: 'ε-Greedy Exploration', desc: '80% exploit top-scored resources + 20% explore to prevent filter bubbles', tag: 'Bandit Algorithms' },
            ].map(algo => (
              <div key={algo.label} className="card shadow-none bg-white">
                <span className="badge badge-indigo mb-3">{algo.tag}</span>
                <h4 className="font-bold text-text-primary text-sm mb-1">{algo.label}</h4>
                <p className="text-xs text-text-secondary leading-relaxed">{algo.desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ── How it works ─────────────────────────────────── */}
      <section className="max-w-6xl mx-auto px-6 py-20">
        <div className="text-center mb-14">
          <h2 className="text-3xl font-bold mb-3 text-text-primary">How it works</h2>
          <p className="text-text-secondary">Four steps from goal to mastery.</p>
        </div>
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6 relative">
          {/* Connector line */}
          <div className="hidden lg:block absolute top-8 left-[12%] right-[12%] h-0.5 bg-surface-300 z-0" />
          {steps.map((s, i) => (
            <motion.div
              key={i}
              initial={{ opacity: 0, y: 16 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.4, delay: i * 0.1 }}
              className="card text-center relative z-10"
            >
              <div className="w-12 h-12 rounded-xl bg-brand-600 text-white font-black text-sm flex items-center justify-center mx-auto mb-4">
                {s.n}
              </div>
              <h3 className="font-bold text-text-primary mb-2 text-sm">{s.title}</h3>
              <p className="text-xs text-text-secondary leading-relaxed">{s.desc}</p>
            </motion.div>
          ))}
        </div>
      </section>

      {/* ── CTA ──────────────────────────────────────────── */}
      <section className="bg-gradient-to-br from-brand-600 to-violet-700 py-20">
        <div className="max-w-2xl mx-auto px-6 text-center">
          <h2 className="text-3xl font-bold text-white mb-3">Ready to start your journey?</h2>
          <p className="text-brand-200 mb-8">
            Join learners building ML-powered paths toward their dream careers.
          </p>
          <div className="flex flex-wrap justify-center gap-4 mb-8 text-sm text-brand-100">
            {['Skill Gap Analysis', 'AI Explanations', 'Adaptive Assessments', 'Progress Dashboard'].map(t => (
              <span key={t} className="flex items-center gap-1.5">
                <CheckCircle className="w-3.5 h-3.5 text-emerald-300" /> {t}
              </span>
            ))}
          </div>
          <Link
            to="/register"
            className="inline-flex items-center gap-2 px-8 py-4 rounded-2xl bg-white text-brand-700 font-bold text-base hover:bg-brand-50 transition-colors shadow-card-lg"
          >
            Get started — it's free <ArrowRight className="w-5 h-5" />
          </Link>
        </div>
      </section>

      {/* ── Footer ───────────────────────────────────────── */}
      <footer className="border-t border-surface-200 py-8 text-center">
        <div className="flex items-center justify-center gap-2 mb-2">
          <div className="w-6 h-6 rounded-lg bg-gradient-to-br from-brand-500 to-violet-600 flex items-center justify-center">
            <Brain className="w-3.5 h-3.5 text-white" />
          </div>
          <span className="font-bold text-text-primary text-sm">PathMind AI</span>
        </div>
        <p className="text-xs text-text-muted">Your goal. Your pace. Your path.</p>
      </footer>
    </div>
  )
}
